

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.superset.serviceName }}
spec:
  type: {{ .Values.superset.serviceType }}
  selector:
    app: {{ .Values.superset.appName }}
  ports:
    - port: {{ .Values.superset.servicePort }}
      # the same value as the `port` field.
      targetPort: {{ .Values.superset.servicetargetPort }}
      # will allocate a port from a range (default: 30000-32767)
      nodePort: {{ .Values.superset.servicenodePort }}